# Generated by Django 4.0.2 on 2022-04-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='issuedate',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='booklist',
            name='studentname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='booklist',
            name='studentno',
            field=models.CharField(default='', max_length=50),
        ),
    ]
