# Generated by Django 4.0.2 on 2022-04-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_alter_booklist_issuedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='issuedate',
            field=models.CharField(default='', max_length=50),
        ),
    ]
